name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  # Build dependencies job
  build-dependencies:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    concurrency:
      group: build-dependencies
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.4
    - name: Cache build venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: /home/runner/work/example-app/.venv
        key: ${{ runner.os }}-venv
    - name: Install deps
      run: poetry install --no-root

  # Static code tests job
  static-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    needs: build-dependencies
    concurrency:
      group: static-tests
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Cache build venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: /home/runner/work/example-app/.venv
        key: ${{ runner.os }}-venv
    - name: Lint
      run: poetry run task lint
    - name: Formatter
      run: poetry run task formatter
    - name: Security
      run: poetry run task security

  # Unit tests job
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    needs: build-dependencies
    concurrency:
      group: unit-tests
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Cache build venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: /home/runner/work/example-app/.venv
        key: ${{ runner.os }}-venv
    - name: Unit Tests
      run: poetry run task test
    - name: Test with pytest
      run: pytest
